// 40 phrases humoristiques FR + EN qui changent à chaque clic
export const phrases = {
  en: [
    "still nothing.",
    "wow. nothing happened.",
    "groundbreaking.",
    "a perfect nothing.",
    "your therapist would be proud.",
    "nothing again? amazing.",
    "you are doing great. doing nothing.",
    "the void approves.",
    "this is the peak of human achievement.",
    "press it again. trust me.",
    "no notification. no point. no problem.",
    "you have unlocked: nothing.",
    "the universe stays the same.",
    "100% nothing, 0% regret.",
    "monks meditate for years to feel this.",
    "doing nothing is also a choice.",
    "you are the chosen one. of nothing.",
    "this could be your job, honestly.",
    "less than zero stuff happened.",
    "the button approves of you.",
    "nothing was harmed.",
    "we counted it. it was nothing.",
    "investors are watching.",
    "elon couldn't do this any better.",
    "your dopamine: confused.",
    "boredom: elevated.",
    "productivity: undefined.",
    "this app passes the turing test of nothing.",
    "you blinked. the button noticed.",
    "imagine explaining this to your mom.",
    "still here. still nothing.",
    "another flawless nothing.",
    "the algorithm cannot save you here.",
    "infinite scroll, finite point.",
    "you have transcended.",
    "the silence is loud.",
    "absolutely zero loot.",
    "you opened the app. for this.",
    "we are out of nothings. just kidding.",
    "okay one more. last one. promise.",
  ],
  fr: [
    "toujours rien.",
    "wow. il s'est rien passé.",
    "révolutionnaire.",
    "un rien parfait.",
    "ta psy serait fière.",
    "encore rien ? incroyable.",
    "tu fais du bon boulot. à rien faire.",
    "le vide approuve.",
    "le sommet de l'humanité.",
    "réappuie. fais-moi confiance.",
    "pas de notif. pas de but. pas de soucis.",
    "tu as débloqué : rien.",
    "l'univers reste pareil.",
    "100% rien, 0% regret.",
    "des moines méditent des années pour ça.",
    "ne rien faire est aussi un choix.",
    "tu es l'élu. de rien.",
    "ça pourrait être ton job, sincèrement.",
    "moins que zéro chose s'est produite.",
    "le bouton t'approuve.",
    "personne n'a été blessé.",
    "on a compté. c'était rien.",
    "les investisseurs regardent.",
    "elon ne ferait pas mieux.",
    "ta dopamine : confuse.",
    "ennui : élevé.",
    "productivité : indéfinie.",
    "cette app passe le test de turing du rien.",
    "tu as cligné. le bouton l'a vu.",
    "imagine expliquer ça à ta mère.",
    "toujours là. toujours rien.",
    "encore un rien impeccable.",
    "l'algo peut pas te sauver ici.",
    "scroll infini, intérêt fini.",
    "tu as transcendé.",
    "le silence est fort.",
    "absolument zéro loot.",
    "tu as ouvert l'app. pour ça.",
    "on est en rupture de rien. nan je rigole.",
    "ok un dernier. le dernier. promis.",
  ],
};

export const i18n = {
  en: {
    streak: "streak",
    total: "total",
    best: "best session",
    session: "session",
    daily_badge: "daily check-in",
    daily_done: "see you tomorrow",
    boosts: "boosts",
    boost_double: "double",
    boost_shield: "streak shield",
    boost_vip: "vip",
    leaderboard: "leaderboard",
    home: "home",
    shop: "shop",
    period_24h: "24h",
    period_7d: "7d",
    period_30d: "30d",
    period_all: "all time",
    cat_streak: "streak",
    cat_session: "session",
    cat_total: "total",
    cat_received: "received",
    cat_sent: "sent",
    you: "you",
    rank: "your rank",
    manifesto_title: "the nothing manifesto",
    manifesto_body: "we live in a world that begs you to do something. to optimize, to post, to grind. nothing is a quiet rebellion. press the button. it does nothing. that is the whole point. and it is glorious.",
    button: "nothing",
    soon: "coming soon",
    pro: "nothing pro",
    search: "search",
    received_toast: "you received a nothing",
    nothings_recv: "received",
    nothings_sent: "sent",
    profile: "profile",
    settings: "settings",
    avatar: "avatar",
    upload: "upload",
    remove: "remove",
    quote: "quote",
    quote_ph: "say nothing, beautifully…",
    username: "username",
    save: "save",
    saved: "saved",
    username_taken: "username taken",
    invalid_username: "3-20 chars, letters/numbers/_",
    sign_out: "sign out",
    member_since: "joined",
  },
  fr: {
    streak: "série",
    total: "total",
    best: "record session",
    session: "session",
    daily_badge: "check-in du jour",
    daily_done: "à demain",
    boosts: "boosts",
    boost_double: "double",
    boost_shield: "bouclier de série",
    boost_vip: "vip",
    leaderboard: "classement",
    home: "accueil",
    shop: "boutique",
    period_24h: "24h",
    period_7d: "7j",
    period_30d: "30j",
    period_all: "all time",
    cat_streak: "série",
    cat_session: "session",
    cat_total: "total",
    cat_received: "reçus",
    cat_sent: "envoyés",
    you: "toi",
    rank: "ton rang",
    manifesto_title: "le manifeste du rien",
    manifesto_body: "on vit dans un monde qui te supplie de faire quelque chose. d'optimiser, de poster, de produire. rien est une rébellion silencieuse. appuie sur le bouton. il ne fait rien. c'est tout l'intérêt. et c'est glorieux.",
    button: "rien",
    soon: "bientôt",
    pro: "nothing pro",
    search: "chercher",
    received_toast: "tu as reçu un rien",
    nothings_recv: "reçus",
    nothings_sent: "envoyés",
    profile: "profil",
    settings: "paramètres",
    avatar: "avatar",
    upload: "uploader",
    remove: "retirer",
    quote: "citation",
    quote_ph: "ne dis rien, joliment…",
    username: "username",
    save: "sauvegarder",
    saved: "sauvegardé",
    username_taken: "username déjà pris",
    invalid_username: "3-20 car, lettres/chiffres/_",
    sign_out: "déconnexion",
    member_since: "inscrit",
  },
} as const;

export type Lang = keyof typeof i18n;
